#!/usr/bin/env python3
"""Rebuild INDEX.md and docs/gallery.html from whatever is in skills/.

    python scripts/build_index.py

Runs automatically on every merge to main, so the catalog is never stale.
"""
from __future__ import annotations

import datetime
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
INDEX = ROOT / "INDEX.md"
GALLERY = ROOT / "docs" / "gallery.html"

SHAPES = {
    "instructions": ("Instructions only", "#6b7fd7"),
    "method": ("Enforces a method", "#8b5cf6"),
    "scripts": ("Ships scripts", "#0f9d58"),
    "knowledge": ("Ships knowledge", "#d97706"),
    "runtime": ("Ships a runtime", "#b11f4b"),
}

sys.path.insert(0, str(ROOT / "scripts"))
from validate_skill import parse_frontmatter  # noqa: E402


def load(path: pathlib.Path) -> dict | None:
    skill_md = path / "SKILL.md"
    if not skill_md.exists():
        return None

    fm = parse_frontmatter(skill_md.read_text(encoding="utf-8")) or {}
    meta_path = path / "meta.yml"
    meta = {}
    if meta_path.exists():
        meta = parse_frontmatter("---\n" + meta_path.read_text(encoding="utf-8") + "\n---\n") or {}

    desc = re.sub(r"\s+", " ", fm.get("description", "")).strip()
    trigger, _, dormant = desc.partition("Does NOT fire on:")

    return {
        "name": fm.get("name", path.name),
        "folder": path.name,
        "description": desc,
        "trigger": trigger.strip(),
        "dormant": dormant.strip(),
        "author": meta.get("author", "unknown"),
        "github": meta.get("github", ""),
        "category": (meta.get("category") or "other").strip(),
        "shape": (meta.get("shape") or "instructions").strip(),
        "tested_on": meta.get("tested_on", ""),
        "date": meta.get("date", ""),
        "has_scripts": (path / "scripts").is_dir(),
        "has_resources": (path / "resources").is_dir(),
    }


def collect() -> list[dict]:
    if not SKILLS.is_dir():
        return []
    out = []
    for p in sorted(SKILLS.iterdir()):
        if p.is_dir() and not p.name.startswith("_"):
            s = load(p)
            if s:
                out.append(s)
    return out


def write_index(skills: list[dict]) -> None:
    today = datetime.date.today().isoformat()
    L: list[str] = []
    L.append("# The Skill Foundry — catalog\n")
    L.append(f"*{len(skills)} skill{'s' if len(skills) != 1 else ''} · rebuilt {today}*\n")
    L.append("> Auto-generated by `scripts/build_index.py`. Do not edit by hand —")
    L.append("> your changes will be overwritten on the next merge.\n")

    if not skills:
        L.append("\nNothing here yet. **[Be the first →](CONTRIBUTING.md)**\n")
        INDEX.write_text("\n".join(L), encoding="utf-8")
        return

    by_cat: dict[str, list[dict]] = {}
    for s in skills:
        by_cat.setdefault(s["category"], []).append(s)

    L.append("\n## At a glance\n")
    L.append("| Skill | What it does | Shape | Author |")
    L.append("|---|---|---|---|")
    for s in skills:
        shape_label = SHAPES.get(s["shape"], ("Instructions only", ""))[0]
        short = s["trigger"][:110] + ("…" if len(s["trigger"]) > 110 else "")
        who = f"[@{s['github']}](https://github.com/{s['github']})" if s["github"] else s["author"]
        L.append(f"| **[{s['name']}](skills/{s['folder']}/)** | {short} | {shape_label} | {who} |")

    L.append("\n---\n")

    for cat in sorted(by_cat):
        L.append(f"\n## {cat.replace('-', ' ').title()}\n")
        for s in by_cat[cat]:
            L.append(f"### [{s['name']}](skills/{s['folder']}/)\n")
            L.append(f"{s['trigger']}\n")
            if s["dormant"]:
                L.append(f"> **Does not fire on:** {s['dormant']}\n")
            bits = []
            if s["has_scripts"]:
                bits.append("ships `scripts/`")
            if s["has_resources"]:
                bits.append("ships `resources/`")
            if s["tested_on"]:
                bits.append(f"tested on {s['tested_on']}")
            if bits:
                L.append(f"*{' · '.join(bits)}*\n")
            L.append(
                f"[SKILL.md](skills/{s['folder']}/SKILL.md) · "
                f"[Evidence](skills/{s['folder']}/EVIDENCE.md)\n"
            )

    L.append("\n---\n")
    L.append("**[← Back to README](README.md)** · **[Add your own →](CONTRIBUTING.md)**\n")
    INDEX.write_text("\n".join(L), encoding="utf-8")


def write_gallery(skills: list[dict]) -> None:
    today = datetime.date.today().isoformat()
    cards = []
    for s in skills:
        label, colour = SHAPES.get(s["shape"], ("Instructions only", "#6b7fd7"))
        tags = []
        if s["has_scripts"]:
            tags.append("scripts")
        if s["has_resources"]:
            tags.append("resources")
        tag_html = "".join(f'<span class="tag">{html.escape(t)}</span>' for t in tags)
        dormant_html = (
            f'<p class="dormant"><b>Does not fire on:</b> {html.escape(s["dormant"])}</p>'
            if s["dormant"] else ""
        )
        who = html.escape(s["author"])
        if s["github"]:
            who = f'<a href="https://github.com/{html.escape(s["github"])}">@{html.escape(s["github"])}</a>'
        cards.append(f"""
      <article class="card" data-cat="{html.escape(s['category'])}" data-name="{html.escape(s['name'].lower())} {html.escape(s['trigger'].lower())}">
        <span class="shape" style="--c:{colour}">{label}</span>
        <h3><a href="../skills/{html.escape(s['folder'])}/SKILL.md">{html.escape(s['name'])}</a></h3>
        <p class="desc">{html.escape(s['trigger'])}</p>
        {dormant_html}
        <div class="tags">{tag_html}</div>
        <footer>
          <span>{who}</span>
          <a class="ev" href="../skills/{html.escape(s['folder'])}/EVIDENCE.md">See it run →</a>
        </footer>
      </article>""")

    cats = sorted({s["category"] for s in skills})
    chips = "".join(
        f'<button class="chip" data-f="{html.escape(c)}">{html.escape(c.replace("-", " "))}</button>'
        for c in cats
    )

    empty = "" if skills else """
      <div class="empty">
        <h2>Nothing forged yet</h2>
        <p>Be the first — see <a href="../CONTRIBUTING.md">CONTRIBUTING.md</a>.</p>
      </div>"""

    GALLERY.parent.mkdir(parents=True, exist_ok=True)
    GALLERY.write_text(f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>The Skill Foundry — gallery</title>
<style>
  :root {{
    --bg:#fbf9f7; --card:#fff; --ink:#1a1a1a; --soft:#6b6b6b;
    --line:#e6e2de; --accent:#b11f4b;
  }}
  @media (prefers-color-scheme:dark) {{
    :root {{ --bg:#151314; --card:#1e1b1c; --ink:#f2efed; --soft:#a09a97;
             --line:#332e30; --accent:#fd8ea1; }}
  }}
  * {{ box-sizing:border-box }}
  body {{ margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif }}
  header {{ padding:48px 24px 28px; text-align:center; border-bottom:1px solid var(--line) }}
  .logos img {{ height:46px; margin:0 16px; vertical-align:middle }}
  h1 {{ margin:18px 0 6px; font-size:30px; letter-spacing:-.02em }}
  .sub {{ color:var(--soft); margin:0 }}
  .bar {{ max-width:1180px; margin:24px auto 0; padding:0 24px;
          display:flex; gap:10px; flex-wrap:wrap; align-items:center }}
  #q {{ flex:1; min-width:220px; padding:10px 14px; border:1px solid var(--line);
        border-radius:8px; background:var(--card); color:var(--ink); font-size:14px }}
  .chip {{ padding:8px 14px; border:1px solid var(--line); border-radius:20px;
           background:var(--card); color:var(--soft); cursor:pointer; font-size:13px }}
  .chip.on {{ background:var(--accent); color:#fff; border-color:var(--accent) }}
  main {{ max-width:1180px; margin:0 auto; padding:24px;
          display:grid; gap:18px; grid-template-columns:repeat(auto-fill,minmax(330px,1fr)) }}
  .card {{ background:var(--card); border:1px solid var(--line); border-radius:12px;
           padding:20px; display:flex; flex-direction:column; gap:10px }}
  .card.hide {{ display:none }}
  .shape {{ align-self:flex-start; font-size:11px; font-weight:600; letter-spacing:.04em;
            text-transform:uppercase; color:var(--c); border:1px solid var(--c);
            border-radius:4px; padding:3px 8px }}
  .card h3 {{ margin:0; font-size:19px }}
  .card h3 a {{ color:var(--ink); text-decoration:none }}
  .card h3 a:hover {{ color:var(--accent) }}
  .desc {{ margin:0; color:var(--soft); font-size:14px }}
  .dormant {{ margin:0; font-size:12.5px; color:var(--soft);
              border-left:2px solid var(--line); padding-left:10px }}
  .tags {{ display:flex; gap:6px; flex-wrap:wrap }}
  .tag {{ font-size:11px; background:var(--bg); border:1px solid var(--line);
          border-radius:4px; padding:2px 7px; color:var(--soft) }}
  .card footer {{ margin-top:auto; padding-top:12px; border-top:1px solid var(--line);
                  display:flex; justify-content:space-between; align-items:center;
                  font-size:13px; color:var(--soft) }}
  .card footer a {{ color:var(--accent); text-decoration:none; font-weight:600 }}
  .empty {{ grid-column:1/-1; text-align:center; padding:70px 20px; color:var(--soft) }}
  footer.pg {{ text-align:center; padding:36px 20px; color:var(--soft); font-size:13px;
               border-top:1px solid var(--line); margin-top:24px }}
</style></head><body>
<header>
  <div class="logos">
    <img src="../assets/jhf-logo.png" alt="JHF"><img src="../assets/comcec-logo.png" alt="COMCEC">
  </div>
  <h1>The Skill Foundry</h1>
  <p class="sub">{len(skills)} skill{'s' if len(skills) != 1 else ''} · built and tested by the cohort · rebuilt {today}</p>
</header>
<div class="bar">
  <input id="q" placeholder="Search by what you need done…" autocomplete="off">
  <button class="chip on" data-f="*">all</button>{chips}
</div>
<main id="grid">{''.join(cards)}{empty}</main>
<footer class="pg">Agentic AI Bootcamp · Jerusalem High-Tech Foundry × COMCEC</footer>
<script>
  const cards=[...document.querySelectorAll('.card')];
  const chips=[...document.querySelectorAll('.chip')];
  const q=document.getElementById('q');
  let filter='*';
  function apply(){{
    const t=q.value.trim().toLowerCase();
    cards.forEach(c=>{{
      const okCat = filter==='*' || c.dataset.cat===filter;
      const okTxt = !t || c.dataset.name.includes(t);
      c.classList.toggle('hide', !(okCat&&okTxt));
    }});
  }}
  chips.forEach(c=>c.onclick=()=>{{
    chips.forEach(x=>x.classList.remove('on'));
    c.classList.add('on'); filter=c.dataset.f; apply();
  }});
  q.oninput=apply;
</script>
</body></html>
""", encoding="utf-8")


def main() -> int:
    skills = collect()
    write_index(skills)
    write_gallery(skills)
    print(f"indexed {len(skills)} skill(s)")
    print(f"  {INDEX.relative_to(ROOT)}")
    print(f"  {GALLERY.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
